name: smart_google_ads_example
description: Example app for smart_google_ads.
publish_to: none

environment:
  sdk: ^3.12.2
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  smart_google_ads:
    path: ../
dev_dependencies:
  flutter_launcher_icons: "^0.14.4"
flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
