name: smart_google_ads_example
description: Example app for smart_google_ads.
publish_to: none

environment:
  sdk: ^3.12.2
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  smart_google_ads:
    path: ../

flutter:
  uses-material-design: true
